on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
name: All actions test
jobs:
  check-current-version:
    name: Check current version
    uses: >-
      NovoNordisk-OpenSource/r.workflows/.github/workflows/check_current_version.yaml@fix/workflow_call
    secrets: inherit
  check-nn-version:
    name: Check NN version
    uses: >-
      NovoNordisk-OpenSource/r.workflows/.github/workflows/check_nn_versions.yaml@fix/workflow_call
    secrets: inherit
  pkgdown:
    name: Pkgdown site
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/pkgdown.yaml@fix/workflow_call
    secrets: inherit
  coverage:
    name: Coverage report
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/coverage.yaml@fix/workflow_call
    secrets: inherit
  megalinter:
    name: Megalinter
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/megalinter.yaml@fix/workflow_call
    secrets: inherit
