# File to run actions
on:
    push:
      branches: [main, master]
    pull_request:
      branches: [main, master]

name: All actions

jobs:

#### For normal workflow
  check-current-version:
    name: Check current version
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/check_current_version.yaml@main
    secrets: inherit

#### For NN workflow
  check-nn-version:
    name: Check NN version
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/check_nn_versions.yaml@main
    secrets: inherit

#### For pkgdown site (with dev feature)
  pkgdown:
    name: Pkgdown site
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/pkgdown.yaml@main
    secrets: inherit

#### For coverage (post in comments)
  coverage:
    name: Coverage report
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/coverage.yaml@main
    secrets: inherit

#### For megalinter (post in comments)
  megalinter:
    name: Megalinter
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/megalinter.yaml@main
    secrets: inherit
